apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
        - name: app
          image: ajayyeruva18/regapp:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 40m
              memory: 50Mi
          resources:
            limits:
              memory: 50Mi
              cpu: 10m
            requests:
              memory: 50Mi
              cpu: 10m
          env:
            - name: DB_CONNECTION_STRING
              value: "test_value"
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: regapp
  namespace: dev
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: regapp
---

